### ISSUE TITLE
Error when compile loader.so

### ISSUE THREAD

**Issue by jinyixin621** [NervanaSystems/neon#158] opened 2015-12-13 15:34 UTC
Compiling neon/data/imageset_decoder.so ...
g++ -w -O3 -shared -o neon/data/imageset_decoder.so -std=c++11 -fPIC neon/data/imageset_decoder.cpp $(pkg-config opencv --cflags --libs)
/usr/bin/ld: cannot find -lcufft

**Comment by jinyixin621** [comment] 2015-12-13 15:34
Any help? Please!

**Comment by apark263** [comment] 2015-12-13 17:02
What version of gcc do you have?

**Comment by scttl** [comment] 2016-01-05 22:02
Closing as there hasn't been a response in 3+ weeks.  If you are still seeing this issue please let us know.  Also this may be related or a dupe of #176

**Closed by scttl** 2016-01-05 22:02 UTC
