### ISSUE TITLE
won't build

### ISSUE THREAD

**Issue by etienne87** [NervanaSystems/neon#197] opened 2016-02-03 16:21 UTC
Hello! I just cloned neon & make. My config is Ubuntu 15.04, so I'm guessing gcc5 could be responsible?

`Building loader.so...
In file included from reader.hpp:31:0,
                 from loader.hpp:28,
                 from loader.cpp:19:
buffer.hpp: In instantiation of ‘T* Buffer<T>::getItem(int, int&) [with T = char]’:
loader.hpp:190:63:   required from here
buffer.hpp:109:19: **error**: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         if (index >= _items.size()) {
      `

**Comment by apark263** [comment] 2016-02-03 16:25
Hi,

We will push a fix for this soon, but in the meantime could you just do a
cast to signed int for that offending line?

Thanks

**Comment by etienne87** [comment] 2016-02-03 16:31
Hello! 

This is just what i did! It builds fine now!

**Comment by scttl** [comment] 2016-02-03 17:29
This looks like a dupe of #180

**Closed** 2016-02-03 17:55 UTC
Labels: bug, duplicate
