### ISSUE TITLE
Custom data, "index 10 is out of bounds for axis 0 with size 10" - custom ArrayIterator

### ISSUE THREAD

**Issue by marcj** [NervanaSystems/neon#201] opened 2016-02-12 21:41 UTC
I'm trying to setup a custom ArrayIterate with own image data, so far I just tried to setup the example given in http://neon.nervanasys.com/docs/latest/datasets.html#add-a-new-dataset.

When I execute the code there

```python
X = np.random.rand(10000,3072)
y = np.random.randint(1,11,10000)
train_set = ArrayIterator(X=X, y=y, nclass=10, lshape=(3,32,32))

valid_set = train_set #just to see if it generally runs

init_norm = Gaussian(loc=0.0, scale=0.01)

# setup model layers
layers = [Affine(nout=100, init=init_norm, activation=Rectlin()),
          Affine(nout=10, init=init_norm, activation=Logistic(shortcut=True))]

# setup cost function as CrossEntropy
cost = GeneralizedCost(costfunc=CrossEntropyBinary())

# setup optimizer
optimizer = GradientDescentMomentum(0.1, momentum_coef=0.9, stochastic_round=args.rounding)

# initialize model object
mlp = Model(layers=layers)

# configure callbacks
callbacks = Callbacks(mlp, eval_set=valid_set, **args.callback_args)

# run fit
mlp.fit(train_set, optimizer=optimizer, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
print('Misclassification error = %.1f%%' % (mlp.eval(valid_set, metric=Misclassification())*100))

```

I get following error

```
    mlp.fit(train_set, optimizer=optimizer, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
  File "/Library/Python/2.7/site-packages/neon/models/model.py", line 137, in fit
    self._epoch_fit(dataset, callbacks)
  File "/Library/Python/2.7/site-packages/neon/models/model.py", line 155, in _epoch_fit
    for mb_idx, (x, t) in enumerate(dataset):
  File "/Library/Python/2.7/site-packages/neon/data/dataiterator.py", line 145, in __iter__
    self.ydev[i1:i2], axis=0)
  File "/Library/Python/2.7/site-packages/neon/backends/nervanacpu.py", line 154, in __setitem__
    self.__getitem__(key)._assign(value)
  File "/Library/Python/2.7/site-packages/neon/backends/nervanacpu.py", line 216, in _assign
    OpTreeNode.build("assign", self, value)
  File "/Library/Python/2.7/site-packages/neon/backends/backend.py", line 2088, in build
    return node.execute()
  File "/Library/Python/2.7/site-packages/neon/backends/backend.py", line 2109, in execute
    return backend.execute(self)
  File "/Library/Python/2.7/site-packages/neon/backends/nervanacpu.py", line 589, in execute
    array_output[numpy_ind.tolist()] = 1
IndexError: index 10 is out of bounds for axis 0 with size 10
```

Did I something wrong here or did I encounter a bug?

I use neon at OSX and `master e7ab2c2` git version.

**Comment by ursk** [comment] 2016-02-12 22:02
If I execute the following code, on a clean checkout of `e7ab2c2`,

```import numpy as np
from neon.backends import gen_backend
from neon.data import ArrayIterator

be = gen_backend()

X = np.random.rand(10000,3072)
y = np.random.randint(1,11,10000)

train = ArrayIterator(X=X, y=y, nclass=10, lshape=(3,32,32))```
it runs without error. Can you confirm that your build environment is clean, in particular since you are running neon from `/Library/Python/2.7/site-packages/neon` and not the recommended virtualenv installation?

**Comment by marcj** [comment] 2016-02-12 22:09
Sorry, I forgot to copy the complete code. It crashes at the `mlp.fit` call. I updated the original post. This osx machine is a few days old, I believe it's clear although I don't know what clean exactly mean and how I can see if its "not clean".

**Comment by ursk** [comment] 2016-02-12 23:14
Hi Marc,
I still had to guess how you set up the model (i.e. backend and command line args), but with the following script I still can't reproduce the issue:
```
#!/usr/bin/env python
import logging

from neon.callbacks.callbacks import Callbacks
from neon.data import ArrayIterator, load_mnist
from neon.initializers import Gaussian
from neon.layers import GeneralizedCost, Affine
from neon.models import Model
from neon.optimizers import GradientDescentMomentum
from neon.transforms import Rectlin, Logistic, CrossEntropyBinary, Misclassification
from neon.util.argparser import NeonArgparser


# parse the command line arguments
parser = NeonArgparser(__doc__)
import numpy as np
args = parser.parse_args()

logger = logging.getLogger()
logger.setLevel(args.log_thresh)

X = np.random.rand(10000,3072)
y = np.random.randint(1,11,10000)
train_set = ArrayIterator(X=X, y=y, nclass=10, lshape=(3,32,32))

valid_set = train_set #just to see if it generally runs

init_norm = Gaussian(loc=0.0, scale=0.01)

# setup model layers
layers = [Affine(nout=100, init=init_norm, activation=Rectlin()),
          Affine(nout=10, init=init_norm, activation=Logistic(shortcut=True))]

# setup cost function as CrossEntropy
cost = GeneralizedCost(costfunc=CrossEntropyBinary())

# setup optimizer
optimizer = GradientDescentMomentum(0.1, momentum_coef=0.9, stochastic_round=args.rounding)

# initialize model object
mlp = Model(layers=layers)

# configure callbacks
callbacks = Callbacks(mlp, eval_set=valid_set, **args.callback_args)

# run fit
mlp.fit(train_set, optimizer=optimizer, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
print('Misclassification error = %.1f%%' % (mlp.eval(valid_set, metric=Misclassification())*100))
```

What my previous comment refers to was that if you have a local folder with the neon repository, e.g. `~/code/neon`, and you git pulled `master e7ab2c2` into that folder, your models will still run on whatever is in `/Library/Python/2.7/site-packages/neon` and _not_ on `~/code/neon`.

**Comment by ursk** [comment] 2016-02-12 23:38
Digging a little bit deeper there is actually a typo in the documentation. Instead of 
`y = np.random.randint(1,11,10000)`
try setting up the labels as 
`y = np.random.randint(0,10,10000)` 
so the class labels can directly map to a 10 dimensional one-hot encoding. Currently, what happens is the CPU backend fails to assign to the 11th row in a 10-dimensional array, and the GPU fails silently. 

Thanks for pointing this out, we will update the docs accordingly and make sure there will be a more informative error message if converting the class-labels to a one-hot encoding fails.

**Comment by marcj** [comment] 2016-02-15 12:39
Thanks Urs for the really fast response! That was indeed the issue. I'm currently trying to build my own train set as already mentioned, but unfortunately I have not much luck yet. The example with train_y of the documentation is a bit strange to me. It generates a list of 10k numbers. I guess each number represents the idx of a output which should get a expected result a maximal activation. (3 => `0001000000`, 0=>`1000000000`, etc), but if I want to have several outputs generate a max activation? like `1001000110`. I can't find any documentation about such use cases. Unfortunately all examples lie behind some data generators which do some magic in other libraries so I don't fully understand yet how x and y data should be exactly shaped and which scenarios are possible.

I have currently a 2d array (65, 14400), 65 examples with each 120x120=14400 as input and output another 2d array (65, 55), 65 examples with each 55 possible categories.

```python
train_set = ArrayIterator(imagesTrainXFixed, imagesTestXFixed, nclass=len(labels), lshape=(1, 120, 120))
valid_set = train_set #just to demo if the network is at min possible to determine the train data itself
```

Here just in case a screenshot of my debugger showing imagesTrainXFixed and imagesTestXFixed.

![neon-example](https://cloud.githubusercontent.com/assets/450980/13048883/4517e5a0-d3e9-11e5-9e09-836a8ee5441d.jpg)

I'm not sure here if I need to adjust somewhere the model so Neon is capable of using my y-data. Currently with these data I get a network which isn't learning anything, constant cost of `38,12` and I really believe this has something to do with the way my y-data looks. Do you have some hint? Maybe some examples I can look at or did I miss some documentation?

**Comment by marcj** [comment] 2016-02-15 15:13
Oh well, I believe I got it. I guess neon is detecting the array shape and transforms it. If you don't say now  I need to call something else additionally to get it working, this can be closed :) Thanks!

**Comment by ursk** [comment] 2016-02-16 17:11
Hi Marc,
sounds like you already got a solution, but I still want to point out that `ArrayIterator` has an optional argument `make_onehot` that defaults to `True`. If you set it to `False`, you can pass in target vectors directly, instead of just passing the index of the target class. Watch out though, some of the costs / metrics only work with one-hot encoded data and might give unexpected results if more than one class is true.

**Closed by ursk** 2016-02-16 17:11 UTC
