### ISSUE TITLE
Loading existing models lead to wrong results

### ISSUE THREAD

**Issue by photoncanon** [NervanaSystems/neon#329] opened 2016-11-23 06:56 UTC
I tried to save and reload a trained model. Then use the loaded model for testing. However, the result I got is different from that of the original model. Here is my code. Where I got wrong?

**...
model1.save_params('model1.p')
model2 = Model(load_obj('model1.p'))
preds1 = model1.get_outputs(test)
preds2 = model2.get_outputs(test)**

My output is a 2-d vector for a training sample for a binary classification task. I expect preds1 and preds2 to be exactly the same. However, preds2 predicts all the samples to be [1,0]. 
At first I doubt if the load_obj fails, so I checked some of the layer parameters by manually checking:
**model1.get_description(True)['model']['config']['layers'][0]['params']['W']**
and 
**model2.get_description(True)['model']['config']['layers'][0]['params']['W']**
To my surprise, they are the same. 
So where could I go wrong? Thanks in advance!

**Comment by hanlin-nervana** [comment] 2017-01-20 18:43
Hello,

Can  you share the model file or script in question? I was unable to reproduce this error with neon v1.8.1 and using the `mnist_mlp.py` example. I appended the following code to the `mnist_mlp.py` script:

```
import numpy as np
mlp.save_params('model1.p')
mlp2 = Model('model1.p')

preds1 = mlp.get_outputs(valid_set)
preds2 = mlp2.get_outputs(valid_set)
print np.allclose(preds1, preds2)
```

I obtained a result `True`.

**Comment by jennifermyers** [comment] 2017-02-22 01:02
Closing this as cannot reproduce. @photoncanon, please reopen with the exact script you are using if you are still having trouble and we can take a look.

**Closed by jennifermyers** 2017-02-22 01:02 UTC
