### ISSUE TITLE
undefined symbol error when loading loader.so

### ISSUE THREAD

**Issue by willtwr** [NervanaSystems/neon#176] opened 2015-12-27 03:43 UTC
I am trying to run ImageLoader but facing some problem here.
I have the loader.so file in the correct location. 
So, I modified imageloader.py to raise the error instead of just asking me to compile loader.so.
Then, I got this message:
OSError: /.../neon/data/loader/loader.so: undefined symbol: _ZN2cv6imreadERKSsi

I am using Ubuntu. 
I had install libopencv-dev and pkg-config using apt-get.

To check opencv, I typed the following in terminal:
pkg-config --modversion opencv
shows 2.4.9

In addition, I had nvcc v7.5.17 installed.

Help is appreciated.

**Comment by Jokeren** [comment] 2016-01-03 04:23
I have a similar problem.

I used g++ v4.8.4, and I tried opencv V2.0.0 and V3.0.0.

I had the message:

    /home/wangcw/src/neon/neon/data/loader/loader.so: undefined symbol:_ZN2cv4flipERKNS_11_InputArrayERKNS_12_OutputArrayEi

**Comment by diyessi** [comment] 2016-01-07 19:29
Since ldd says loader.so is okay, this could be a problem with how symbols are resolved when the library is loaded.  Do either of you have a relatively simple python program you could share that exhibits the problem?

**Comment by jennifermyers** [comment] 2016-05-02 16:57
Closing this as we have been unable to reproduce. Please reopen if it happens again.

**Closed by jennifermyers** 2016-05-02 16:57 UTC

**Comment by Jokeren** [comment] 2016-05-03 05:06
@jennifermyers, Actually I fixed this problem a few months ago. Finally I noticed that it was caused by inconsistency among versions of libraries needed by opencv. After configuring them to the same version, it worked as I expected. 

So you are right, it is a very specific problem.

**Comment by jennifermyers** [comment] 2016-05-03 14:51
Thank you @Jokeren for the followup!
